"""
Deterministic financial reconciliation engine for Chimera.

This module compares transactions against settlements, invoices,
and payouts without using an LLM.
"""

from __future__ import annotations

from collections import Counter
from typing import Any


AMOUNT_TOLERANCE = 0.01


def reconcile_financial_data(
    data: dict[str, list[dict[str, Any]]],
) -> list[dict[str, Any]]:
    """
    Reconcile transactions against settlements, invoices, and payouts.

    Args:
        data: Financial datasets generated by data_generator.py.

    Returns:
        A list containing one reconciliation result per transaction.
    """

    transactions = data.get("transactions", [])
    settlements = data.get("settlements", [])
    invoices = data.get("invoices", [])
    payouts = data.get("payouts", [])

    settlement_by_transaction = _index_by_transaction(
        settlements,
        "transaction_id",
    )

    invoice_by_transaction = _index_by_transaction(
        invoices,
        "transaction_id",
    )

    payout_by_transaction = _index_by_transaction(
        payouts,
        "transaction_id",
    )

    transaction_counts = Counter(
        transaction.get("transaction_id")
        for transaction in transactions
    )

    results: list[dict[str, Any]] = []

    for transaction in transactions:
        transaction_id = transaction.get("transaction_id")

        issues: list[str] = []

        amount = _safe_float(transaction.get("amount"))

        if amount is None:
            issues.append("MALFORMED_TRANSACTION_AMOUNT")

        if transaction_counts[transaction_id] > 1:
            issues.append("DUPLICATE_TRANSACTION")

        settlement = settlement_by_transaction.get(transaction_id)
        invoice = invoice_by_transaction.get(transaction_id)
        payout = payout_by_transaction.get(transaction_id)

        if settlement is None:
            issues.append("MISSING_SETTLEMENT")
        else:
            settlement_amount = _safe_float(
                settlement.get("settlement_amount")
            )

            if settlement.get("status") == "MISSING":
                issues.append("MISSING_SETTLEMENT")

            if settlement_amount is None:
                issues.append("MALFORMED_SETTLEMENT_AMOUNT")
            elif amount is not None:
                expected_fee = round(amount * 0.02, 2)
                expected_settlement = round(
                    amount - expected_fee,
                    2,
                )

                if not _amounts_match(
                    settlement_amount,
                    expected_settlement,
                ):
                    issues.append("SETTLEMENT_AMOUNT_MISMATCH")

                actual_fee = _safe_float(settlement.get("fee"))

                if actual_fee is None:
                    issues.append("MALFORMED_FEE")
                elif not _amounts_match(
                    actual_fee,
                    expected_fee,
                ):
                    issues.append("INCORRECT_FEE")

            if settlement.get("settlement_date") == "2026-09-15":
                issues.append("DELAYED_SETTLEMENT")

        if invoice is None:
            issues.append("MISSING_INVOICE")
        else:
            invoice_amount = _safe_float(
                invoice.get("invoice_amount")
            )

            if invoice_amount is None:
                issues.append("MALFORMED_INVOICE_AMOUNT")
            elif amount is not None:
                if not _amounts_match(invoice_amount, amount):
                    issues.append("INVOICE_AMOUNT_MISMATCH")

        if payout is None:
            issues.append("MISSING_PAYOUT")
        else:
            payout_amount = _safe_float(
                payout.get("payout_amount")
            )

            if payout.get("status") == "MISSING":
                issues.append("MISSING_PAYOUT")

            if payout_amount is None:
                issues.append("MALFORMED_PAYOUT_AMOUNT")
            elif amount is not None:
                expected_fee = round(amount * 0.02, 2)
                expected_payout = round(
                    amount - expected_fee,
                    2,
                )

                if payout_amount < expected_payout:
                    issues.append("PARTIAL_SETTLEMENT")

                elif not _amounts_match(
                    payout_amount,
                    expected_payout,
                ):
                    issues.append("PAYOUT_AMOUNT_MISMATCH")

        if transaction_id and transaction_id.startswith("TXN-UNKNOWN"):
            issues.append("UNKNOWN_TRANSACTION")

        status = "MATCHED" if not issues else "EXCEPTION"

        results.append(
            {
                "transaction_id": transaction_id,
                "status": status,
                "issues": sorted(set(issues)),
                "transaction_amount": amount,
                "currency": transaction.get("currency", "INR"),
            }
        )

    return results


def _index_by_transaction(
    records: list[dict[str, Any]],
    transaction_key: str,
) -> dict[str, dict[str, Any]]:
    """
    Create a transaction ID → record index.

    If duplicate records exist, the first record is retained.
    """

    indexed: dict[str, dict[str, Any]] = {}

    for record in records:
        transaction_id = record.get(transaction_key)

        if transaction_id is None:
            continue

        if transaction_id not in indexed:
            indexed[transaction_id] = record

    return indexed


def _safe_float(value: Any) -> float | None:
    """
    Convert a value to float safely.

    Invalid financial values return None instead of crashing.
    """

    if isinstance(value, bool):
        return None

    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _amounts_match(
    actual: float,
    expected: float,
) -> bool:
    """Compare two financial amounts using a small tolerance."""

    return abs(actual - expected) <= AMOUNT_TOLERANCE


if __name__ == "__main__":
    from backend.finance.data_generator import generate_financial_data

    financial_data = generate_financial_data()

    results = reconcile_financial_data(financial_data)

    matched = sum(
        result["status"] == "MATCHED"
        for result in results
    )

    exceptions = sum(
        result["status"] == "EXCEPTION"
        for result in results
    )

    print("CHIMERA FINANCE RECONCILIATION")
    print("=" * 40)
    print(f"Records processed : {len(results)}")
    print(f"Matched           : {matched}")
    print(f"Exceptions        : {exceptions}")